### ISSUE TITLE
USO - Atualizar README.md

### ISSUE THREAD

**Issue by future2back** [cleitonleonel/Pyfood#1]
Fala @cleitonleonel tranquilo? Quais os principais uso desta ferramenta? Voce poderia atualizar o readme com a instalacao e uso por favor? Obrigado.

Abracos.

**Comment by cleitonleonel** [comment]
@future2back tudo tranquilo sim, respondendo suas perguntas...a ferramenta em questão possui funcionalidades de um ouvinte, isso mesmo, um ouvinte de pedidos para lojas que possuam integração com ifood, ou seja, ao receber um pedido de um cliente o pyfood ouve esse pedido e o salva em cache, abrindo opções de gerenciar esse pedido, como confirmar ou não o pedido e enviar para preparo, funciona exatamente como o gerenciador de pedidos do ifood, mas claro sem tantas funcionalidades e sem uma interface gráfica.
Quanto a segunda pergunta posso sim atualizar o readme lá, mas a questão da instalação é simples, vc pode clonar o projeto com ```git clone https://github.com/cleitonleonel/Pyfood.git``` ou ```pip3 install git+https://github.com/cleitonleonel/Pyfood.git``` .
De todo modo para usar essa ferramenta vc precisa obter as credenciais de acesso ao gestor de pedidos, usuário e senha...mais informações vc pode encontrar dentro do readme do próprio módulo [pyfood](https://github.com/cleitonleonel/Pyfood/blob/master/Ifood/readme).
Basicamente vc só precisa mesmo de um usuário e senha para acessar o sistema de gerenciamentos do ifood os mesmos utilizados para acessar o gestor de pedidos como especificado no exemplo que vc encontra no readme do módulo.
A grosso modo segue um exemplo:

client_id: iconnect_v3_homologation #  DEIXAR COMO ESTÁ
client_secret: PR2#!HxY #  DEIXAR COMO ESTÁ
username: #  REQUER USUÁRIO, O MESMO UTILIZADO NO GERENCIADOR DE PEDIDOS
password: #  REQUER SENHA, A MESMA UTILIZADA NO GERENCIADOR DE PEDIDOS
grant_type: password #  DEIXAR COMO ESTÁ

De todo modo irei deixar isso mais explícito no readme principal do projeto, qualquer dúvida ou sugestão enviar no e-mail cleiton.leonel@gmail.com.

**Comment by future2back** [comment]
fala @cleitonleonel bom dia irmao. tudo bem?

Esse teu projeto serviria de caminho para um integracao do iFood com o Woocommerce? Utilizar apenas o ouvinte para jogar direto os pedidos na API do Woocommerce?


Abracos.

**Comment by cleitonleonel** [comment]
Bom dia, creio que sim, teria que fazer uma modificação no tratamento dos
dados obtidos do ifood, pois nesse projeto aí eu tive que tratar a reposta
do ifood de modo que ela fosse consumida por um sistema escrito em
clipper...então bastaria modificar a forma como esses dados são tratados.

Em seg., 16 de mai. de 2022 às 06:35, future2back ***@***.***>
escreveu:
